### ISSUE TITLE
Initial project setup with Next.js + Tailwind

### ISSUE THREAD

**Issue by notrab** [notrab/jamstackforum#2]
* PurgeCSS
* Inter font
* Next google fonts dep

**Comment by ashikvarma11** [comment]
@notrab I would like to initiate the project development. COuld you assign me this?

**Comment by swapnadeepmohapatra** [comment]
Hey @notrab , I any interested to work on this issue. Can you please assign me this.

**Comment by notrab** [comment]
Hey @ashikvarma11 @swapnadeepmohapatra I'm about to stream the initial setup of this today soon, as well as continue setting up issues for tasks. Happy to collab on this.
