### ISSUE TITLE
Deploy to vercel error

### ISSUE THREAD

**Issue by jingtaiboke** [notrab/jamstackforum#59]
`

2:01:54 | > Build error occurred
-- | --
12:01:54 | TypeError: Only absolute URLs are supported
12:01:54 | at getNodeRequestOptions (/vercel/workpath0/node_modules/node-fetch/lib/index.js:1299:9)
12:01:54 | at /vercel/workpath0/node_modules/node-fetch/lib/index.js:1404:19
12:01:54 | at new Promise (<anonymous>)
12:01:54 | at Object.fetch (/vercel/workpath0/node_modules/node-fetch/lib/index.js:1401:9)
12:01:54 | at Object.fetch [as default] (/vercel/workpath0/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
12:01:54 | at GraphQLClient.<anonymous> (/vercel/workpath0/node_modules/graphql-request/dist/index.js:138:67)
12:01:54 | at step (/vercel/workpath0/node_modules/graphql-request/dist/index.js:44:23)
12:01:54 | at Object.next (/vercel/workpath0/node_modules/graphql-request/dist/index.js:25:53)
12:01:54 | at /vercel/workpath0/node_modules/graphql-request/dist/index.js:19:71
12:01:54 | at new Promise (<anonymous>) {

`

**Comment by notrab** [comment]
@jingtaiboke the error `TypeError: Only absolute URLs are supported` would suggest your GraphQL endpoint is not configured correctly.

Do you have this set? `NEXT_PUBLIC_HASURA_API_ENDPOINT` and `HASURA_GRAPHQL_ADMIN_SECRET`
