### ISSUE TITLE
Create simple page layout

### ISSUE THREAD

**Issue by notrab** [notrab/jamstackforum#6]
It would be worth creating a simple layout to have links to the index page, auth functions, and pages for today's posts, answered, and unanswered posts.

It may also be worth fetching all categories in a dropdown for the header.

**Comment by js899** [comment]
Hello @notrab Is this a webapp you need ? Can I start designing the layout using html, css/bootstrap, js ? I'll make it responsive for mobile also.

**Comment by notrab** [comment]
Hey @js899 I'm about to stream the initial setup and layout soon. We'll be using TailwindCSS if you want to contribute to further issues as I figure out how we do this app for Hacktoberfest.
