### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by bikkimahato** [notrab/jamstackforum#62]
In the place of username the email validation error message is being shown.
Ideally both should be separate or if the error message is combined then it can be shown above the username or below the email.
![image](https://user-images.githubusercontent.com/42492682/154967020-6fe2a149-23ae-4139-baa0-1f397b490c20.png)

**Comment by notrab** [comment]
I think this is meant to be an email, and the error is just a built in browser validation error. 

Happy to merge any PRa that fix this. 

Thanks!
